#Simple game By Rishikesh Joshi
import time
print('This programme consists of a few simple and interactive math puzzles. Take your time to solve the questions')
time.sleep(2.5)
print('Here is the first puzzle\n')
time.sleep(2.5)
print('I am a single digit\n')
time.sleep(2.5)
print('When you write me I have no start and no end\n')
time.sleep(2.5)
print('I am like a pair of glasses on my side .....\n')
time.sleep(2.5)
print('Who am I? Enter your answer below\n')
time.sleep(0.5)
x = float(input('Type your answer here :'))
if x == 8:
    print('Correct!!\n')
else:
    print('Take your time, try to answer it correctly the next time you run this programme XD\n')
time.sleep(2)
print('Proceeding to the next question\n')
time.sleep(2)
print('I am a 2 digit number\n')
time.sleep(2)
print('The sum of each of my digits is 8\n')
time.sleep(2)
print('My second digit is 2 more than my first one.....\n')
time.sleep(2)
print('Who am I? Enter your answer below\n')
time.sleep(1)
y = float(input('Type your answer here :'))
if y == 35:
    print('Great job! 35 is the correct answer\n')
else:
    print('Try again next time. Do not lose hope :)\n')
time.sleep(2)
print('Moving on to the final question\n')
time.sleep(2)
print('There were some people on the train\n')
time.sleep(2)
print('19 people get off the train at the first stop\n')
time.sleep(2)
print('17 people get on the train at the same stop\n')
time.sleep(2)
print('Now there are 63 people on the train\n')
time.sleep(2)
print('How many people were on the train to begin with? Answer below\n')
time.sleep(1)
z = float(input('Type your answer here :'))
if z == 65:
    print('Yes, 65 is the right answer!')
    time.sleep(1.5)
    print('This is the end of the game... Thanks for participating :)')
else:
    print('Incorrect answer.... better luck next time')
time.sleep(0.5)
print('*****Game over*****')
